export const fullCurrency = {
  "1inch": "1inch",
  "aave": "Aave",
  "ada": "Cardano",
  "aed": "United Arab Emirates Dirham",
  "afn": "Afghan Afghani",
  "akt": "Akash Network",
  "algo": "Algorand",
  "all": "Albanian Lek",
  "amd": "Armenian Dram",
  "amp": "Amp",
  "ang": "Netherlands Antillean Guilder",
  "aoa": "Angolan Kwanza",
  "ape": "ApeCoin",
  "apt": "Aptos",
  "ar": "Arweave",
  "arb": "Arbitrum",
  "ars": "Argentine Peso",
  "atom": "Cosmos",
  "ats": "Austrian Schilling",
  "aud": "Australian Dollar",
  "avax": "Avalanche",
  "awg": "Aruban Florin",
  "axs": "Axie Infinity",
  "azm": "Azerbaijani Manat (Old)",
  "azn": "Azerbaijani Manat",
  "bake": "BakeryToken",
  "bam": "Bosnia-Herzegovina Convertible Mark",
  "bat": "Basic Attention Token",
  "bbd": "Barbadian Dollar",
  "bch": "Bitcoin Cash",
  "bdt": "Bangladeshi Taka",
  "bef": "Belgian Franc",
  "bgn": "Bulgarian Lev",
  "bhd": "Bahraini Dinar",
  "bif": "Burundian Franc",
  "bmd": "Bermudian Dollar",
  "bnb": "BNB",
  "bnd": "Brunei Dollar",
  "bob": "Bolivian Boliviano",
  "brl": "Brazilian Real",
  "bsd": "Bahamian Dollar",
  "bsv": "Bitcoin SV",
  "bsw": "Biswap",
  "btc": "Bitcoin",
  "btcb": "Bitcoin BEP2",
  "btg": "Bitcoin Gold",
  "btn": "Bhutanese Ngultrum",
  "btt": "BitTorrent",
  "busd": "Binance USD",
  "bwp": "Botswanan Pula",
  "byn": "Belarusian Ruble",
  "byr": "Belarusian Ruble (Old)",
  "bzd": "Belize Dollar",

  "cad": "Canadian Dollar",
  "cake": "PancakeSwap",
  "cdf": "Congolese Franc",
  "celo": "Celo",
  "cfx": "Conflux",
  "chf": "Swiss Franc",
  "chz": "Chiliz",
  "clp": "Chilean Peso",
  "cnh": "Chinese Yuan Offshore",
  "cny": "Chinese Yuan",
  "comp": "Compound",
  "cop": "Colombian Peso",
  "crc": "Costa Rican Colón",
  "cro": "Cronos",
  "crv": "Curve DAO Token",
  "cspr": "Casper",
  "cuc": "Cuban Convertible Peso",
  "cup": "Cuban Peso",
  "cve": "Cape Verdean Escudo",
  "cvx": "Convex Finance",
  "cyp": "Cypriot Pound",
  "czk": "Czech Koruna",

  "dai": "Dai",
  "dash": "Dash",
  "dcr": "Decred",
  "dem": "German Mark",
  "dfi": "DeFiChain",
  "djf": "Djiboutian Franc",
  "dkk": "Danish Krone",
  "doge": "Dogecoin",
  "dop": "Dominican Peso",
  "dot": "Polkadot",
  "dydx": "dYdX",
  "dzd": "Algerian Dinar",

  "eek": "Estonian Kroon",
  "egld": "MultiversX",
  "egp": "Egyptian Pound",
  "enj": "Enjin Coin",
  "eos": "EOS",
  "ern": "Eritrean Nakfa",
  "esp": "Spanish Peseta",
  "etb": "Ethiopian Birr",
  "etc": "Ethereum Classic",
  "eth": "Ethereum",
  "eur": "Euro",
  "eurc": "Euro Coin",
  "fei": "Fei USD",
  "fil": "Filecoin",
  "fim": "Finnish Markka",
  "fjd": "Fijian Dollar",
  "fkp": "Falkland Islands Pound",
  "flow": "Flow",
  "flr": "Flare",
  "frax": "Frax",
  "frf": "French Franc",
  "ftt": "FTX Token",

  "gala": "Gala",
  "gbp": "British Pound Sterling",
  "gel": "Georgian Lari",
  "ggp": "Guernsey Pound",
  "ghc": "Ghanaian Cedi (Old)",
  "ghs": "Ghanaian Cedi",
  "gip": "Gibraltar Pound",
  "gmd": "Gambian Dalasi",
  "gmx": "GMX",
  "gnf": "Guinean Franc",
  "gno": "Gnosis",
  "grd": "Greek Drachma",
  "grt": "The Graph",
  "gt": "GateToken",
  "gtq": "Guatemalan Quetzal",
  "gusd": "Gemini Dollar",
  "gyd": "Guyanese Dollar",

  "hbar": "Hedera",
  "hkd": "Hong Kong Dollar",
  "hnl": "Honduran Lempira",
  "hnt": "Helium",
  "hot": "Holo",
  "hrk": "Croatian Kuna",
  "ht": "Huobi Token",
  "htg": "Haitian Gourde",
  "huf": "Hungarian Forint",

  "icp": "Internet Computer",
  "idr": "Indonesian Rupiah",
  "iep": "Irish Pound",
  "ils": "Israeli New Shekel",
  "imp": "Isle of Man Pound",
  "imx": "Immutable X",
  "inj": "Injective",
  "inr": "Indian Rupee",
  "iqd": "Iraqi Dinar",
  "irr": "Iranian Rial",
  "isk": "Icelandic Króna",
  "itl": "Italian Lira",

  "jep": "Jersey Pound",
  "jmd": "Jamaican Dollar",
  "jod": "Jordanian Dinar",
  "jpy": "Japanese Yen",

  "kas": "Kaspa",
  "kava": "Kava",
  "kcs": "KuCoin Token",
  "kda": "Kadena",
  "kes": "Kenyan Shilling",
  "kgs": "Kyrgystani Som",
  "khr": "Cambodian Riel",
  "klay": "Klaytn",
  "kmf": "Comorian Franc",
  "knc": "Kyber Network Crystal",
  "kpw": "North Korean Won",
  "krw": "South Korean Won",
  "ksm": "Kusama",
  "kwd": "Kuwaiti Dinar",
  "kyd": "Cayman Islands Dollar",
  "kzt": "Kazakhstani Tenge",

  "lak": "Laotian Kip",
  "lbp": "Lebanese Pound",
  "ldo": "Lido DAO",
  "leo": "LEO Token",
  "link": "Chainlink",
  "lkr": "Sri Lankan Rupee",
  "lrc": "Loopring",
  "lrd": "Liberian Dollar",
  "lsl": "Lesotho Loti",
  "ltc": "Litecoin",
  "ltl": "Lithuanian Litas",
  "luf": "Luxembourg Franc",
  "luna": "Terra",
  "lunc": "Terra Classic",
  "lvl": "Latvian Lats",
  "lyd": "Libyan Dinar",

  "mad": "Moroccan Dirham",
  "mana": "Decentraland",
  "mbx": "MARBLEX",
  "mdl": "Moldovan Leu",
  "mga": "Malagasy Ariary",
  "mgf": "Malagasy Franc",
  "mina": "Mina",
  "mkd": "Macedonian Denar",
  "mkr": "Maker",
  "mmk": "Myanmar Kyat",
  "mnt": "Mongolian Tögrög",
  "mop": "Macanese Pataca",
  "mro": "Mauritanian Ouguiya (Old)",
  "mru": "Mauritanian Ouguiya",
  "mtl": "Maltese Lira",
  "mur": "Mauritian Rupee",
  "mvr": "Maldivian Rufiyaa",
  "mwk": "Malawian Kwacha",
  "mxn": "Mexican Peso",
  "mxv": "Mexican Unidad de Inversion",
  "myr": "Malaysian Ringgit",
  "mzm": "Mozambican Metical (Old)",
  "mzn": "Mozambican Metical",

  "nad": "Namibian Dollar",
  "near": "NEAR Protocol",
  "neo": "NEO",
  "nexo": "Nexo",
  "nft": "NFT",
  "ngn": "Nigerian Naira",
  "nio": "Nicaraguan Córdoba",
  "nlg": "Dutch Guilder",
  "nok": "Norwegian Krone",
  "npr": "Nepalese Rupee",
  "nzd": "New Zealand Dollar",

  "okb": "OKB",
  "omr": "Omani Rial",
  "one": "Harmony",
  "op": "Optimism",
  "ordi": "ORDI",

  "pab": "Panamanian Balboa",
  "paxg": "PAX Gold",
  "pen": "Peruvian Sol",
  "pepe": "Pepe",
  "pgk": "Papua New Guinean Kina",
  "php": "Philippine Peso",
  "pi": "Pi Network",
  "pkr": "Pakistani Rupee",
  "pln": "Polish Złoty",
  "pol": "Polygon",
  "pte": "Portuguese Escudo",
  "pyg": "Paraguayan Guarani",

  "qar": "Qatari Riyal",
  "qnt": "Quant",
  "qtum": "Qtum",

  "rol": "Romanian Leu (Old)",
  "ron": "Romanian Leu",
  "rpl": "Rocket Pool",
  "rsd": "Serbian Dinar",
  "rub": "Russian Ruble",
  "rune": "THORChain",
  "rvn": "Ravencoin",
  "rwf": "Rwandan Franc",

  "sand": "The Sandbox",
  "sar": "Saudi Riyal",
  "sbd": "Solomon Islands Dollar",
  "scr": "Seychellois Rupee",
  "sdd": "Sudanese Dinar",
  "sdg": "Sudanese Pound",
  "sek": "Swedish Krona",
  "sgd": "Singapore Dollar",
  "shib": "Shiba Inu",
  "shp": "Saint Helena Pound",
  "sit": "Slovenian Tolar",
  "skk": "Slovak Koruna",
  "sle": "Sierra Leonean Leone",
  "sll": "Sierra Leonean Leone (Old)",
  "snx": "Synthetix",
  "sol": "Solana",
  "sos": "Somali Shilling",
  "spl": "Seborgan Luigino",
  "srd": "Surinamese Dollar",
  "srg": "Surinamese Guilder",
  "ssp": "South Sudanese Pound",
  "std": "São Tomé and Príncipe Dobra (Old)",
  "stn": "São Tomé and Príncipe Dobra",
  "stx": "Stacks",
  "sui": "Sui",
  "svc": "Salvadoran Colón",
  "syp": "Syrian Pound",
  "szl": "Swazi Lilangeni",

  "thb": "Thai Baht",
  "theta": "Theta Network",
  "tjs": "Tajikistani Somoni",
  "tmm": "Turkmenistani Manat (Old)",
  "tmt": "Turkmenistani Manat",
  "tnd": "Tunisian Dinar",
  "ton": "Toncoin",
  "top": "Tongan Paʻanga",
  "trl": "Turkish Lira (Old)",
  "trx": "TRON",
  "try": "Turkish Lira",
  "ttd": "Trinidad and Tobago Dollar",
  "tusd": "TrueUSD",
  "tvd": "Tuvaluan Dollar",
  "twd": "New Taiwan Dollar",
  "twt": "Trust Wallet Token",
  "tzs": "Tanzanian Shilling",

  "uah": "Ukrainian Hryvnia",
  "ugx": "Ugandan Shilling",
  "uni": "Uniswap",
  "usd": "US Dollar",
  "usdc": "USD Coin",
  "usdd": "USDD",
  "usdp": "Pax Dollar",
  "usdt": "Tether",
  "uyu": "Uruguayan Peso",
  "uzs": "Uzbekistani Soʻm",

  "val": "Vatican Lira",
  "veb": "Venezuelan Bolívar (Old)",
  "ved": "Venezuelan Digital Bolívar",
  "vef": "Venezuelan Bolívar Fuerte",
  "ves": "Venezuelan Bolívar",
  "vet": "VeChain",
  "vnd": "Vietnamese Đồng",
  "vuv": "Vanuatu Vatu",

  "waves": "Waves",
  "wemix": "WEMIX",
  "woo": "WOO Network",
  "wst": "Samoan Tala",

  "xaf": "Central African CFA Franc",
  "xag": "Silver",
  "xau": "Gold",
  "xaut": "Tether Gold",
  "xbt": "Bitcoin",
  "xcd": "East Caribbean Dollar",
  "xcg": "Caribbean Guilder",
  "xch": "Chia",
  "xdc": "XDC Network",
  "xdr": "Special Drawing Rights",
  "xec": "eCash",
  "xem": "NEM",
  "xlm": "Stellar",
  "xmr": "Monero",
  "xof": "West African CFA Franc",
  "xpd": "Palladium",
  "xpf": "CFP Franc",
  "xpt": "Platinum",
  "xrp": "XRP",
  "xtz": "Tezos",

  "yer": "Yemeni Rial",

  "zar": "South African Rand",
  "zec": "Zcash",
  "zil": "Zilliqa",
  "zmk": "Zambian Kwacha (Old)",
  "zmw": "Zambian Kwacha",
  "zwd": "Zimbabwean Dollar",
  "zwg": "Zimbabwe Gold",
  "zwl": "Zimbabwean Dollar"
};